#!/bin/sh
# Assemble index.html from the section chunks in sections/.
# No framework, no dependencies — just concatenation. The committed index.html
# is plain static HTML that GitHub Pages serves directly; this script is only an
# authoring convenience so each section can be edited in its own file.
#
# Usage:  ./build.sh        (run from the repo root; re-run after editing sections/)

set -eu
cd "$(dirname "$0")"

OUT="index.html"
SECTIONS="home music plugins research about"

{
  printf '<!-- GENERATED by build.sh from sections/*.html — do not edit directly. -->\n'
  cat "sections/_head.html"
  for s in $SECTIONS; do
    printf '\n'
    cat "sections/$s.html"
  done
  printf '\n'
  cat "sections/_foot.html"
} > "$OUT"

echo "Wrote $OUT from: _head + $SECTIONS + _foot"
